### ISSUE TITLE
MICA PermissionError: [Errno 13] Permission denied: 'prep.py'

### ISSUE THREAD

**Issue by jiangzh-coder** [jyyulab/scMINER#16]
Hi i met following error when i run MICA:

(omicverse6) root@jiang:/home/jzhou/MICA/MICA/bin# mica mds -i /mnt/c/@@@@@@@@TCF1_T_scATAC/new/CD8TMICA.h5ad -o /mnt/c/@@@@@@@@TCF1_T_scATAC/new/ -pn TRAMP -nc 16
INFO:root:Start MDS mode...
INFO:root:/mnt/c/@@@@@@@@TCF1_T_scATAC/new/mica.yml
INFO:root:infile:
  class: File
  path: /mnt/c/@@@@@@@@TCF1_T_scATAC/new/CD8TMICA.h5ad
project_name: TRAMP
k: [16]
num_neighbor: None
visualization: UMAP
dim_reduction: MDS
iterations_km: 10
dims_km: [19]
dims: 19
dims_plot: 19
perplexity: 30
min_dist: 0.6
slice_size: 1000
thread_number: 10
dist_metrics: mi

INFO:root:cwltool --leave-tmpdir --outdir /mnt/c/@@@@@@@@TCF1_T_scATAC/new/ /root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/cwl/mica.cwl /mnt/c/@@@@@@@@TCF1_T_scATAC/new/mica.yml
INFO /root/miniconda3/envs/omicverse6/bin/cwltool 3.0.20210124104916
INFO Resolved '/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/cwl/mica.cwl' to 'file:///root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/cwl/mica.cwl'
INFO [workflow ] start
INFO [workflow ] starting step prep
INFO [step prep] start
INFO [job prep] /tmp/yaoonq_5$ prep.py \
    -i \
    /tmp/29l_o7i3/stg1f004596-266a-4d71-b37b-9a6a03ba4e1f/CD8TMICA.h5ad \
    -o \
    TRAMP \
    -s \
    1000
ERROR Exception while running job
Traceback (most recent call last):
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/cwltool/job.py", line 388, in _execute
    default_stderr=runtimeContext.default_stderr,
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/cwltool/job.py", line 948, in _job_popen
    universal_newlines=True,
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'prep.py'
WARNING [job prep] completed permanentFail
ERROR [step prep] Output is missing expected field file:///root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/cwl/mica.cwl#prep/mat_pair_array
WARNING [step prep] completed permanentFail
INFO [workflow ] completed permanentFail
{
    "clustering_plots": null,
    "clustering_res": null,
    "initial_plots": null,
    "mi.h5": null,
    "mi.reduced": null
}
WARNING Final process status is permanentFail
Traceback (most recent call last):
  File "/root/miniconda3/envs/omicverse6/bin/mica", line 33, in <module>
    sys.exit(load_entry_point('MICA==0.2.2', 'console_scripts', 'mica')())
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/mica.py", line 96, in main
    mica_mds.mica_mds(args)
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/mica_mds.py", line 122, in mica_mds
    run_shell_command_call(cmd)
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/mica_mds.py", line 162, in run_shell_command_call
    subprocess.check_call(cmd_to_exec)
  File "/root/miniconda3/envs/omicverse6/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cwltool', '--leave-tmpdir', '--outdir', '/mnt/c/@@@@@@@@TCF1_T_scATAC/new/', '/root/miniconda3/envs/omicverse6/lib/python3.7/site-packages/MICA/cwl/mica.cwl', '/mnt/c/@@@@@@@@TCF1_T_scATAC/new/mica.yml']' returned non-zero exit status 1.
(omicverse6) root@jiang:/home/jzhou/MICA/MICA/bin#

Can you help me?

best
Jiang

**Comment by QingfeiPan** [comment]
Hi @jiangzh-coder,

Thanks for your feedback! This issue has been fixed in MICA-1.0.0 available at https://github.com/jyyulab/MICA.

Best,
Qingfei
